dyngen_config = {
    "train_batch_size": 50,
    "finetune_batch_size": 10,
    "transfer_batch_size": 10,
    "train_epochs": 40,
    "finetune_epochs": 20,
    "transfer_epochs": 2,
    # "train_task": "supervised_group_identification",
    "train_task": "supervised_group_identification_only",
    # "finetune_task": "cross_model_prediction_clas",
    # "finetune_task": "supervised_group_identification",
    # "transfer_task": "supervised_group_identification",
    "train_loss_weight": None,
    "finetune_loss_weight": None,
    "transfer_loss_weight": None,
    "lr": 0.1,
    "checkpoint": 1,
    "n_head": 1,
    "noise_level": [0, 0, 0, 0],
    "fuser_type": "WeightedMean",
    "encoders": [
        {
            "input": 100,
            # "hiddens": [256, 128, 64],
            "hiddens": [64],
            "output": 50,
            "use_biases": [False, False, False, False],
            "dropouts": [0, 0, 0, 0],
            "activations": ["relu", "relu", "relu", None],
            "use_batch_norms": [True, True, True, True],
            "use_layer_norms": [False, False, False, False],
            "is_binary_input": False,
        },
        {
            "input": 100,
            # "hiddens": [256, 128, 64],
            "hiddens": [64],
            "output": 50,
            "use_biases": [False, False, False, False],
            "dropouts": [0, 0, 0, 0],
            "activations": ["relu", "relu", "relu", None],
            "use_batch_norms": [True, True, True, True],
            "use_layer_norms": [False, False, False, False],
            "is_binary_input": False,
        },
        {
            "input": 100,
            # "hiddens": [256, 128, 64],
            "hiddens": [64],
            "output": 50,
            "use_biases": [False, False, False, False],
            "dropouts": [0, 0, 0, 0],
            "activations": ["relu", "relu", "relu", None],
            "use_batch_norms": [True, True, True, True],
            "use_layer_norms": [False, False, False, False],
            "is_binary_input": False,
        },
        {
            "input": 100,
            # "hiddens": [256, 128, 64],
            "hiddens": [64],
            "output": 50,
            "use_biases": [False, False, False, False],
            "dropouts": [0, 0, 0, 0],
            "activations": ["relu", "relu", "relu", None],
            "use_batch_norms": [True, True, True, True],
            "use_layer_norms": [False, False, False, False],
            "is_binary_input": False,
        },
    ],
    "latent_projector": None,
    "decoders": [
        {
            "input": 50,
            # "hiddens": [64, 128, 256],
            "hiddens": [64],
            "output": 100,
            "use_biases": [False, False, False, False],
            "dropouts": [0, 0, 0, 0],
            "activations": ["relu", "relu", "sigmoid", None],
            "use_batch_norms": [True, True, True, False],
            "use_layer_norms": [False, False, False, False],
        },
        {
            "input": 50,
            # "hiddens": [64, 128, 256],
            "hiddens": [64],
            "output": 100,
            "use_biases": [False, False, False, False],
            "dropouts": [0, 0, 0, 0],
            "activations": ["relu", "relu", "sigmoid", None],
            "use_batch_norms": [True, True, True, False],
            "use_layer_norms": [False, False, False, False],
        },
        {
            "input": 50,
            # "hiddens": [64, 128, 256],
            "hiddens": [64],
            "output": 100,
            "use_biases": [False, False, False, False],
            "dropouts": [0, 0, 0, 0],
            "activations": ["relu", "relu", "sigmoid", None],
            "use_batch_norms": [True, True, True, False],
            "use_layer_norms": [False, False, False, False],
        },
        {
            "input": 50,
            # "hiddens": [64, 128, 256],
            "hiddens": [64],
            "output": 100,
            "use_biases": [False, False, False, False],
            "dropouts": [0, 0, 0, 0],
            "activations": ["relu", "relu", "sigmoid", None],
            "use_batch_norms": [True, True, True, False],
            "use_layer_norms": [False, False, False, False],
        },
    ],
    "discriminators": [
        {
            "input": 100,
            "hiddens": [64, 32],
            "output": 1,
            "use_biases": [False, False, False],
            "dropouts": [0, 0, 0],
            "activations": ["relu", "relu", "sigmoid"],
            "use_batch_norms": [False, False, False],
            "use_layer_norms": [False, False, False],
        },
        {
            "input": 100,
            "hiddens": [64, 32],
            "output": 1,
            "use_biases": [False, False, False],
            "dropouts": [0, 0, 0],
            "activations": ["relu", "relu", "sigmoid"],
            "use_batch_norms": [False, False, False],
            "use_layer_norms": [False, False, False],
        },
        {
            "input": 100,
            "hiddens": [64, 32],
            "output": 1,
            "use_biases": [False, False, False],
            "dropouts": [0, 0, 0],
            "activations": ["relu", "relu", "sigmoid"],
            "use_batch_norms": [False, False, False],
            "use_layer_norms": [False, False, False],
        },
        {
            "input": 100,
            "hiddens": [64, 32],
            "output": 1,
            "use_biases": [False, False, False],
            "dropouts": [0, 0, 0],
            "activations": ["relu", "relu", "sigmoid"],
            "use_batch_norms": [False, False, False],
            "use_layer_norms": [False, False, False],
        },
    ],
    "projectors": {
        "input": 50,
        "hiddens": [],
        "output": 100,
        "use_biases": [False],
        "dropouts": [0],
        "activations": [None],
        "use_batch_norms": [False],
        "use_layer_norms": [False],
    },
    "clusters": {
        "input": 100,
        "hiddens": [],
        "output": 3,
        "use_biases": [False],
        "dropouts": [0],
        "activations": [None],
        "use_batch_norms": [False],
        "use_layer_norms": [False],
    },
}
